### ISSUE TITLE
7.14 会話履歴を保持するの章で、スレッドのやり取りが記憶できない

### ISSUE THREAD

**Issue by HiromichiMatsui** [yoshidashingo/langchain-book#13]
**エラーの説明**
P.180でスレッドのやり取りを記憶できない。

**スクリーンショット**
@ChatCompletion わたしの名前は****です
ChatCompletion
はじめまして、****さん。どのようにお手伝いできますか？ （編集済み） 
@ChatCompletion 私の名前を呼んでください
ChatCompletion
もちろん、[ユーザーの名前]さん。どのようにお手伝いできますか？ （編集済み）

ec2-user:~/environment/slackapp-chatgpt (main) $ python app.py
⚡ Bolt app is running!
Error in SlackStreamingCallbackHandler.on_llm_new_token callback: 'WebClient' object has no attribute 'chat_updat'
Error in SlackStreamingCallbackHandler.on_llm_new_token callback: 'WebClient' object has no attribute 'chat_updat'

**書籍の該当箇所**
7.12会話履歴を保持するの、def handle_mention(event, say):を書き換えたところで、会話の履歴が憶えられていない。

**環境**

AWS Cloud9
Slack
Momento

**その他**
Momento のサインアップは、A.5の方法でトークンを作成しました。トークンは生成できましたが、Authトークンではなく、
API KEYが出力された。.envに、MOMENTO_AUTH_TOKEN=にAPI KEYを記入しました。
今回の演算を行いましたが、オペレーションはカウントされていて問題ないようです。

**Comment by os1ma** [comment]
ご質問ありがとうございます。

会話履歴の保持がうまくいかない場合、app.pyのコードに何か不備がある可能性が高そうです。

### （1）ファイルの保存を確認

まず、app.pyを編集後、保存したか確認してみてください。

### （2）動作確認済みのソースコードで動作確認

書籍の7.12「会話履歴を保持する」の時点のソースコードは以下になります。
https://github.com/yoshidashingo/langchain-book/blob/main/details/07-12_history/app.py

このソースコードを使ってもうまく動作しないか確認してみてください。

### もしも上記の内容で解決しない場合

もしも上記の内容で解決しない場合、以下を共有いただければサポートさせていただきます。

- app.pyの内容
- Cloud9でapp.pyを開いている様子の画面キャプチャ
- pip freezeコマンドの実行結果

よろしくお願いします。

**Comment by HiromichiMatsui** [comment]
回答ありがとうございます。７.12「会話履歴を保持する」の時点のソースコードをコピーして実行しました。エラーコードは出ませんでしたが、slackで@ChatCompletionと会話をしても、私の名前を憶えて、呼びかけることはできませんでした。
[cloud9画面.pdf](https://github.com/yoshidashingo/langchain-book/files/14234669/cloud9.pdf)

**Comment by os1ma** [comment]
状況共有ありがとうございます。

## （1）状況を確認する方法

会話履歴がLLMを呼び出すプロンプトに反映されているか確認するため、LLMを呼び出すときの `messages` を見てみるのがよいと思います。

以下の手順を試してみてください。

1. 以下のように、LLMを呼び出す直前に `print(messages)` を追加したする

```python
    callback = SlackStreamingCallbackHandler(channel=channel, ts=ts)
    llm = ChatOpenAI(
        model_name=os.environ["OPENAI_API_MODEL"],
        temperature=os.environ["OPENAI_API_TEMPERATURE"],
        streaming=True,
        callbacks=[callback],
    )

+   print(messages)
    ai_message = llm(messages)
    history.add_message(ai_message)
```

2. `python app.py` を実行し直す
3. 「わたしの名前は○○です」「わたしの名前を覚えていますか」と会話する
4. ターミナルの表示内容を確認して、LLMを呼び出すときのプロンプトに会話履歴が含まれているか確認する

## （2）プロンプトには会話履歴が含まれているのに応答がうまくいかない場合

プロンプトには会話履歴が含まれているのに応答がうまくいかない場合、単にLLMの性能不足な可能性があります。
gpt-3.5-turboではなくgpt-4を使うとうまく応答を得られるかもしれません。

.envファイルのOPENAI_API_MODELを `gpt-4` に変更して、アプリを起動しなおして、もう一度やりとりを試してみてください。

## もしも上記の内容で解決しない場合

もしも上記の内容で解決しない場合、以下を共有いただければサポートさせていただきます。

- 上記の（1）を試したときのターミナルの画面キャプチャ
- Slackでチャットボットとやり取りする様子の全体が分かる画面キャプチャ

よろしくお願いします。

**Comment by HiromichiMatsui** [comment]
ありがとうございます。
ターミナルの表示内容を確認すると、LLMを呼び出すときのプロンプトに会話履歴が含まれていませんでした。
ターミナルの画面とSlackのチャット画面をキャプチャした結果を添付します。
[claud9画面.pdf](https://github.com/yoshidashingo/langchain-book/files/14254588/claud9.pdf)

**Comment by os1ma** [comment]
状況共有ありがとうございます。

本書の実装での会話履歴の保存は「スレッドごと」になります。
そのため、**`@ChatCompletion わたしの名前は○○です` と `@ChatCompletion わたしの名前を覚えていますか` という投稿は、同じスレッドで実施してください。**

会話履歴の保存がスレッドごとになるのは、app.pyの以下の箇所で、スレッドの先頭の投稿のIDをキーとして保存しているためです。

```python
@app.event("app_mention")
def handle_mention(event, say):
        :
    thread_ts = event["ts"]
        :
    # 投稿のキー(=Momentoキー)：初回=event["ts"],2回目以降=event["thread_ts"]
    id_ts = event["ts"]
    if "thread_ts" in event:
        id_ts = event["thread_ts"]
        :
    history = MomentoChatMessageHistory.from_client_params(
        id_ts,
        os.environ["MOMENTO_CACHE"],
        timedelta(hours=int(os.environ["MOMENTO_TTL"])),
    )
```

同じスレッド内で `@ChatCompletion わたしの名前は○○です` と `@ChatCompletion わたしの名前を覚えていますか` という投稿をして、そのとき、会話履歴を踏まえて応答してくれるか、ターミナルにprintで出力した内容は会話履歴が含まれているか、を確認してみてください。

よろしくお願いします。

**Comment by HiromichiMatsui** [comment]
ありがとうございます。
スレッド内で投稿をやり取りすれば、会話履歴は継承されていました。
画面をPDFで添付しました。
お忙しいところ、ご教示いただき、ありがとうございました。
[cloud9画面.pdf](https://github.com/yoshidashingo/langchain-book/files/14255579/cloud9.pdf)

**Comment by os1ma** [comment]
解決してよかったです！
