### ISSUE TITLE
p74 LLMS

### ISSUE THREAD

**Issue by nekonisi** [yoshidashingo/langchain-book#14]
**エラーの説明**
発生したエラーについて説明してください。
エラーメッセージは省略せず、全文を掲載してください。

該当コード
```python
from langchain.llms import OpenAI

llm = OpenAI(model_name="text-davinci-003", temperature=0)

result = llm("自己紹介してください。")
print(result)
```

エラーメッセージ
```
---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
[<ipython-input-3-8e35423ede4a>](https://localhost:8080/#) in <cell line: 5>()
      3 llm = OpenAI(model_name="text-davinci-003", temperature=0)
      4 
----> 5 result = llm("自己紹介してください。")
      6 print(result)

17 frames
[/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    763         stream_error = stream and "error" in resp.data
    764         if stream_error or not 200 <= rcode < 300:
--> 765             raise self.handle_error_response(
    766                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    767             )

InvalidRequestError: The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations
```

**スクリーンショット**

できるだけ、エラーのスクリーンショットを共有してください。
![image](https://github.com/yoshidashingo/langchain-book/assets/37826501/a43a18c5-c097-4667-8863-56ff025b91c1)

**書籍の該当箇所**

書籍のどの章のどの箇所でエラーが発生したのか記載してください。
例えば書籍のどのページかを記載いただくと、対応がスムーズになります。

|ページ|該当項目|
|-------|----------|
|p74    | LLMS     |

**書籍の内容以外で実施したこと**

書籍の内容以外で何か実施した場合、その内容も記載してください。
たとえば書籍と違う手順でコマンドを実行した場合は、分かる範囲で実行したコマンド・手順を記載してください。

- なし

**環境**

Google Colab

**その他**

エラーの解決のため、その他ご自身で試したことや、確認したログなどがあれば記載してください。
> OpenAIのCompletions APIはすでにLegacyとされています

- という記述があるので問題ないと思いますが、念の為ご報告いたします。
- 書籍分かりやすく、大変感謝しております。

**Comment by os1ma** [comment]
丁寧な共有ありがとうございます。

共有いただいたエラーは "The model `text-davinci-003` has been deprecated" ということで、「text-davinci-003」というモデルの廃止が原因になります。
代替として現在は「gpt-3.5-turbo-instruct」というモデルを使うことになっています。
なお、Completions API自体は、Legacyとされていますが、現在も使用可能です。

参考

- https://platform.openai.com/docs/models/gpt-3-5-turbo
- https://platform.openai.com/docs/deprecations/2023-07-06-gpt-and-embeddings

このGitHubリポジトリの「langchain-v0.1」というブランチで、最近までのアップデートに対応したソースコードを公開しています。
その中では「gpt-3.5-turbo-instruct」を使用していますので、参考にしてください。

https://github.com/yoshidashingo/langchain-book/blob/langchain-v0.1/chapter4/notebook.ipynb

LangChain v0.1 に対応したソースコードの追加については以下を参照してください。

https://github.com/yoshidashingo/langchain-book/blob/langchain-v0.1/updates.md

よろしくお願いします！
