### ISSUE TITLE
P74 LLMsのコードでエラー

### ISSUE THREAD

**Issue by tmdoi** [yoshidashingo/langchain-book#19]
**P74 LLMsのコードでエラー**

---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
[<ipython-input-3-8e35423ede4a>](https://localhost:8080/#) in <cell line: 5>()
      3 llm = OpenAI(model_name="text-davinci-003", temperature=0)
      4 
----> 5 result = llm("自己紹介してください。")
      6 print(result)

17 frames
[/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py](https://localhost:8080/#) in __call__(self, prompt, stop, callbacks, tags, metadata, **kwargs)
    829             )
    830         return (
--> 831             self.generate(
    832                 [prompt],
    833                 stop=stop,

[/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py](https://localhost:8080/#) in generate(self, prompts, stop, callbacks, tags, metadata, **kwargs)
    625                 for callback_manager, prompt in zip(callback_managers, prompts)
    626             ]
--> 627             output = self._generate_helper(
    628                 prompts, stop, run_managers, bool(new_arg_supported), **kwargs
    629             )

[/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py](https://localhost:8080/#) in _generate_helper(self, prompts, stop, run_managers, new_arg_supported, **kwargs)
    527             for run_manager in run_managers:
    528                 run_manager.on_llm_error(e)
--> 529             raise e
    530         flattened_outputs = output.flatten()
    531         for manager, flattened_output in zip(run_managers, flattened_outputs):

[/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py](https://localhost:8080/#) in _generate_helper(self, prompts, stop, run_managers, new_arg_supported, **kwargs)
    514         try:
    515             output = (
--> 516                 self._generate(
    517                     prompts,
    518                     stop=stop,

[/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py](https://localhost:8080/#) in _generate(self, prompts, stop, run_manager, **kwargs)
    383                 )
    384             else:
--> 385                 response = completion_with_retry(
    386                     self, prompt=_prompts, run_manager=run_manager, **params
    387                 )

[/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py](https://localhost:8080/#) in completion_with_retry(llm, run_manager, **kwargs)
    113         return llm.client.create(**kwargs)
    114 
--> 115     return _completion_with_retry(**kwargs)
    116 
    117 

[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in wrapped_f(*args, **kw)
    287         @functools.wraps(f)
    288         def wrapped_f(*args: t.Any, **kw: t.Any) -> t.Any:
--> 289             return self(f, *args, **kw)
    290 
    291         def retry_with(*args: t.Any, **kwargs: t.Any) -> WrappedFn:

[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in __call__(self, fn, *args, **kwargs)
    377         retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)
    378         while True:
--> 379             do = self.iter(retry_state=retry_state)
    380             if isinstance(do, DoAttempt):
    381                 try:

[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in iter(self, retry_state)
    312         is_explicit_retry = fut.failed and isinstance(fut.exception(), TryAgain)
    313         if not (is_explicit_retry or self.retry(retry_state)):
--> 314             return fut.result()
    315 
    316         if self.after is not None:

[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in result(self, timeout)
    449                     raise CancelledError()
    450                 elif self._state == FINISHED:
--> 451                     return self.__get_result()
    452 
    453                 self._condition.wait(timeout)

[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in __get_result(self)
    401         if self._exception:
    402             try:
--> 403                 raise self._exception
    404             finally:
    405                 # Break a reference cycle with the exception in self._exception

[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in __call__(self, fn, *args, **kwargs)
    380             if isinstance(do, DoAttempt):
    381                 try:
--> 382                     result = fn(*args, **kwargs)
    383                 except BaseException:  # noqa: B902
    384                     retry_state.set_exception(sys.exc_info())  # type: ignore[arg-type]

[/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py](https://localhost:8080/#) in _completion_with_retry(**kwargs)
    111     @retry_decorator
    112     def _completion_with_retry(**kwargs: Any) -> Any:
--> 113         return llm.client.create(**kwargs)
    114 
    115     return _completion_with_retry(**kwargs)

[/usr/local/lib/python3.10/dist-packages/openai/api_resources/completion.py](https://localhost:8080/#) in create(cls, *args, **kwargs)
     23         while True:
     24             try:
---> 25                 return super().create(*args, **kwargs)
     26             except TryAgain as e:
     27                 if timeout is not None and time.time() > start + timeout:

[/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py](https://localhost:8080/#) in create(cls, api_key, api_base, api_type, request_id, api_version, organization, **params)
    151         )
    152 
--> 153         response, _, api_key = requestor.request(
    154             "post",
    155             url,

[/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in request(self, method, url, params, headers, files, stream, request_id, request_timeout)
    296             request_timeout=request_timeout,
    297         )
--> 298         resp, got_stream = self._interpret_response(result, stream)
    299         return resp, got_stream, self.api_key
    300 

[/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response(self, result, stream)
    698         else:
    699             return (
--> 700                 self._interpret_response_line(
    701                     result.content.decode("utf-8"),
    702                     result.status_code,

[/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    763         stream_error = stream and "error" in resp.data
    764         if stream_error or not 200 <= rcode < 300:
--> 765             raise self.handle_error_response(
    766                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    767             )

InvalidRequestError: The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations

**スクリーンショット**

できるだけ、エラーのスクリーンショットを共有してください。

**書籍の該当箇所**

P74 LLMsのコードでエラー

**書籍の内容以外で実施したこと**

ChatGPTに聞いたら，
エラーメッセージによれば、InvalidRequestErrorが発生しており、原因は使用しているモデルtext-davinci-003が非推奨（deprecated）となっているためです。OpenAIは定期的にモデルを更新し、古いモデルを非推奨とすることがあります。このような場合、非推奨とされたモデルは利用できなくなり、新しいモデルへの移行が必要になります。

対処方法としては、以下のステップを踏むことをお勧めします：

最新のモデル情報を確認する： OpenAIの公式ドキュメントやAPIの更新情報を確認し、現在利用可能な最新のモデルを把握してください。

モデルを更新する： コード内のmodel_nameパラメータを、利用可能な最新のモデルに更新してください。例えば、text-davinci-003の代わりにtext-davinci-004やgpt-3.5-turboなど、新しいモデルを指定します。

コードの実行： モデルを更新した後、再度コードを実行して、期待通りの動作をするか確認してください。

例として、モデルをtext-davinci-003からtext-davinci-004に更新する場合、コードは以下のようになります：

~~~
from langchain.llms import OpenAI

llm = OpenAI(model_name="text-davinci-004", temperature=0)  # モデル名を更新

result = llm("自己紹介してください。")
print(result)
~~~

**環境**

Google Colab

**その他**

エラーの解決のため、モデルを004にして　実行しましたが，だめでした．

よろしくお願い致します．

**Comment by os1ma** [comment]
ご質問ありがとうございます。

以下のIssueと同様のエラーになりますので、そちらを参照してください。

https://github.com/yoshidashingo/langchain-book/issues/14

よろしくお願いします。

**Comment by tmdoi** [comment]
#14 で対応しましたが，エラーが出ました．

どうも　今日時点では，”gpt-3.5-turbo-instruct”はNGのようです．

いまは，model_name="gpt-3.5-turbo"　とするようです．

**Comment by os1ma** [comment]
今改めて確認しましたが、やはりgpt-3.5-turboではなくgpt-3.5-turbo-instructで正しいです。

ChatOpenAIクラスではgpt-3.5-turboを使うことができますが、質問いただいていたOpenAIクラスではgpt-3.5-turbo-instructを使うことができます。

もし気になる場合は動作させたコードを共有いただければ確認させていただきます。
よろしくお願いします。

**Comment by tmdoi** [comment]
お世話になります．
以下，実行したプログラムとエラーです．

Google Colabで実行しています．
初心者のため，Google Colabの使い方が，おかしいのかもしれません．

よろしくお願い致します．
〜〜〜
import os
os.environ["OPENAI_API_KEY"] = "Key"

!pip install langchain==0.0.292 openai==0.28.0

from langchain.llms import OpenAI
llm = OpenAI(model_name="gpt-3.5-turbo-instruct", temperature=0)
result = llm("自己紹介してください。")
print(result)
〜〜〜〜

エラーメッセージ
---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
[<ipython-input-20-122c58703afb>](https://localhost:8080/#) in <cell line: 5>()
      3 llm = OpenAI(model_name="gpt-3.5-turbo-instruct", temperature=0)
      4 
----> 5 result = llm("自己紹介してください。")
      6 print(result)

17 frames
[/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    763         stream_error = stream and "error" in resp.data
    764         if stream_error or not 200 <= rcode < 300:
--> 765             raise self.handle_error_response(
    766                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    767             )

InvalidRequestError: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

**Comment by os1ma** [comment]
状況共有ありがとうございます。

> !pip install langchain==0.0.292 openai==0.28.0

langchainのバージョン0.0.292はgpt-3.5-turbo-instructに対応していません。

gpt-3.5-turbo-instructを試す際は、以下のノートブックを参考に、gpt-3.5-turbo-instructに対応したバージョンのlangchainをインストールして使用してください。

https://github.com/yoshidashingo/langchain-book/blob/langchain-v0.1/chapter4/notebook.ipynb

補足になりますが、Google Colabでパッケージの別バージョンをインストールする際は、一度環境（ランタイム）を削除して作り直すと確実です。
もしもうまくいかない際は、一度環境（ランタイム）を削除して作り直す操作も試してみてください。

よろしくお願いします。
