### ISSUE TITLE
p.249 リポジトリのクローンについて

### ISSUE THREAD

**Issue by momendoufu** [yoshidashingo/langchain-book#2]
**エラーの説明**
以下該当箇所のリポジトリのクローンに関して，リポジトリの所有者が`os1ma`となっていますが，正しくは本リポジトリの`yoshidashingo`ではないでしょうか．
誤：`git clone git@github.com:os1ma/langchain-book.git`
↓
正：`git clone git@github.com:yoshidashingo/langchain-book.git`

**書籍の該当箇所**
p.249 付録A3

**Comment by os1ma** [comment]
@momendoufu 
ご指摘ありがとうございます！

書籍の該当箇所は、この「yoshidashingo/langchain-book」というリポジトリをクローンするという意図ではなく、ご自身で作成したリポジトリをクローンする手順になります。

そのため、

```
git clone git@github.com:<GitHubのユーザー名>/langchain-book.git
```

のように記載するのが適切そうですね。

正誤表にこのように追記させていただきます！

**Comment by os1ma** [comment]
正誤表を更新しました。

https://github.com/yoshidashingo/langchain-book/commit/dde59d0d03c5ecdf1fa69fc41f687eea66e1f4f8

問題なさそうでしたらこのIssueはクローズさせていただきます。
