### ISSUE TITLE
Slackアプリから返答がない

### ISSUE THREAD

**Issue by aino-capm** [yoshidashingo/langchain-book#6]
**エラーの説明**
173ページの上段、
チャンネル内でSlackアプリにメンションまではできたのですが、アプリからの返答がありません。
よろしくお願いします。

ちなみにターミナルでは以下のメッセージが出ます。
メッセージの通りにコードを書き換えてもエラー解消しません。

⚡ Bolt app is running!
Unhandled request ({'type': 'event_callback', 'event': {'type': 'app_mention'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("app_mention")
def handle_app_mention_events(body, logger):
    [logger.info](http://logger.info/)(body)

発生したエラーについて説明してください。
エラーメッセージは省略せず、全文を掲載してください。

**書籍の該当箇所**

書籍のどの章の本のタイトル : ChatGPT/LangChainによるチャットシステム構築［実践］入門
ページ : 173

**環境**

AWS Cloud9

**その他**

エラーの解決のため、その他ご自身で試したことや、確認したログなどがあれば記載してください。

**Comment by os1ma** [comment]
ご質問ありがとうございます。

共有いただいたエラーメッセージから、以下の点を確認していただくとよさそうです。（とくに1〜3のどれかの可能性が高そうです）

1. app.pyのソースコードにミス（例えばタイプミス）がないか
2. app.pyのソースコードを書き換えたあと、保存したか
3. app.pyを書き換えたあと、`python app.py` コマンドを実行し直したか
4. Slackの管理画面上の設定が不足していないか

app.pyファイルの内容を共有いただければ、何かミスがないかこちらでも確認させていただきます。
app.pyファイルは、GitHubにアップロードしていただいても大丈夫ですし、こちらに貼り付けていただいても大丈夫です。

よろしくお願いします。

**Comment by aino-capm** [comment]
app.pyファイルです。
よろしくお願いします。

import os
from dotenv import load_dotenv
from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler

load_dotenv()

#ボットトークンとソケットモードハンドラーを使ってアプリを初期化
app = App(token=os.environ.get("SLACK_BOT_TOKEN"))

#ソケットモードハンドラーを使ってアプリを起動
if __name__ == "__main__":
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).start()

@app.event("app_mention")
def handle_mention(event, say):
    user = event["user"]
    # thread_ts = event["ts"]
    say(f"Hello<@{user}>!")

@app.event("app_mention")
def handle_app_mention_events(body, logger):
    logger.info(body)

**Comment by aino-capm** [comment]
ありがとうございます
確かに、そうでした。初歩的なミスでした。

それで、ご指摘のとおり、修正したのですが、やはりSLACKアプリから返答がありません。
以下がターミナルで出ているメッセージです。
よろしくお願いします。

Unhandled request ({'type': 'event_callback', 'event': {'type': 'app_mention'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("app_mention")
def handle_app_mention_events(body, logger):
    logger.info(body)

Unhandled request ({'type': 'event_callback', 'event': {'type': 'app_mention'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("app_mention")
def handle_app_mention_events(body, logger):
    logger.info(body)

**Comment by os1ma** [comment]
状況共有ありがとうございます。

ソースコードを修正してもうまくいかない場合、やはり以下のどれかが原因でないか確認していただくのがよさそうです。（とくに1〜3のどれかの可能性が高そうです）

1. app.pyのソースコードにミス（例えばタイプミス）がないか
2. app.pyのソースコードを書き換えたあと、保存したか
3. app.pyを書き換えたあと、`python app.py` コマンドを実行し直したか
4. Slackの管理画面上の設定が不足していないか

上記の内容を確認していただいて、それでもうまく行かない場合、以下を共有いただきたいです。（1〜3に問題がないか確認する内容です）

- app.pyファイルの内容が表示されている画面キャプチャ
- `cat app.py` コマンドの実行結果
- `cat app.py` コマンドの後、`python app.py` コマンドを実行し直して、Slackに `@<ボット名> hello` などと投稿しても応答がないか

よろしくお願いします！

**Comment by aino-capm** [comment]
ありがとうございます。
今試したら、返答してくれました。

**Comment by os1ma** [comment]
よかったです！
