### ISSUE TITLE
7.17 (P187)デプロイ後のエラー・7.18（P188)AWS Lambdaのコンソール

### ISSUE THREAD

**Issue by aino-capm** [yoshidashingo/langchain-book#7]
**エラーの説明**
先日はありがとうございました。
おかげさまで少し前進しました。
ただ、またエラーが出ました。

2点あります。
稚拙な質問で申し訳ありませんがよろしくご教示ください。

1点目：P187
7.17の4デプロイを実行したところ、以下のエラーが出ました。
**デプロイに失敗しているように見えるのですが、いかがでしょうか。**

2点目:P188
次ページのP188でAWS Lambdaのコンソールにアクセスしたのですが、**書籍に記載のようなURLが見当たりません**。
そもそも、書籍に記載のようなAWS Lambdaの画面にどうやって辿り着けばよいのかが分からなく、URLがどこに書いてあるのか教えていただければありがたく（書籍を読み返したのですが、見当たらないです）
普通にコンソールを検索してたどり着いた画面をスクショに添付します。

DOTENV: Loading environment variables from .env:
         - SLACK_SIGNING_SECRET
         - SLACK_BOT_TOKEN
         - SLACK_APP_TOKEN
         - OPENAI_API_KEY
         - OPENAI_API_MODEL
         - OPENAI_API_TEMPERATURE
         - MOMENTO_AUTH_TOKEN
         - MOMENTO_CACHE
         - MOMENTO_TTL

Deploying LangChainBook-ChatGPTSlackFunction to stage dev (ap-northeast-1)

× Stack LangChainBook-ChatGPTSlackFunction-dev failed to deploy (133s)
Environment: linux, node 18.17.1, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: AppLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: Lambda, Status Code: 400, Request ID: cd856b36-e247-4ead-b900-d9bb904284ff)" (RequestToken: 87539eda-ebdb-d826-f82f-a7bb578c5847, HandlerErrorCode: InvalidRequest)

View the full error: https://ap-northeast-1.console.aws.amazon.com/cloudformation/home?region=ap-northeast-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aap-northeast-1%3A123082653093%3Astack%2FLangChainBook-ChatGPTSlackFunction-dev%2F570ab3d0-8bfd-11ee-a649-0e475b115c21

**スクリーンショット**

デプロイ後のエラーの画面
<img width="1181" alt="image" src="https://github.com/yoshidashingo/langchain-book/assets/96915861/f4972d93-ba3c-44b6-aaec-aaf71acaa870">

AWS Lambdaの画面
<img width="1377" alt="image" src="https://github.com/yoshidashingo/langchain-book/assets/96915861/8de170ae-1b29-4a50-9ed8-431d50399393">

**書籍の該当箇所**
P187・188

**書籍の内容以外で実施したこと**

書籍の内容以外で何か実施した場合、その内容も記載してください。
たとえば書籍と違う手順でコマンドを実行した場合は、分かる範囲で実行したコマンド・手順を記載してください。

**環境**

AWS Cloud9（AWS Cloud9 以外の環境を使用している場合はご記入ください）

**その他**

エラーの解決のため、その他ご自身で試したことや、確認したログなどがあれば記載してください。

**Comment by os1ma** [comment]
ご質問ありがとうございます。

### 1点目：P187

> 7.17の4デプロイを実行したところ、以下のエラーが出ました。
> デプロイに失敗しているように見えるのですが、いかがでしょうか。

おっしゃる通り、エラーによってデプロイに失敗したという状況になります。

エラーメッセージに `Unzipped size must be smaller than 262144000 bytes` と書かれており、Lambda関数にデプロイしようとしたファイルサイズが、最大の250MBを超えていることが原因のようです。

`serverless deploy` コマンドを実行したとき、requirements.txtファイルに書かれたPythonパッケージが一緒にデプロイされるのですが、そのPythonパッケージが大きすぎる、という状況だと思います。

おそらく、pip installしたパッケージのバージョンが書籍と異なる（または書籍にないパッケージをインストールした）という状況だと思います。

書籍の通りのバージョンのPythonパッケージを使うため、requirements.txtファイルの内容を、GitHubで公開している見本（[こちら](https://github.com/yoshidashingo/langchain-book/blob/main/chapter7/requirements.txt)）で置き換えて、その後 `serverless deploy` を実行していただくと、デプロイが成功する可能性が高そうです。


### 2点目:P188

> 次ページのP188でAWS Lambdaのコンソールにアクセスしたのですが、書籍に記載のようなURLが見当たりません。
> そもそも、書籍に記載のようなAWS Lambdaの画面にどうやって辿り着けばよいのかが分からなく、URLがどこに書いてある> のか教えていただければありがたく（書籍を読み返したのですが、見当たらないです）
> 普通にコンソールを検索してたどり着いた画面をスクショに添付します。

こちらは、上記のデプロイに失敗していることが原因で、Lambda関数が表示されていない、という状況になります。
デプロイに成功すると画面キャプチャを共有いただいたAWS Lambdaの画面に関数が追加されるので、デプロイに成功してから見るようにしてみてください。

### デプロイのエラーが解決しない場合

デプロイのエラーが解決しない場合、requirements.txtファイルの内容を共有いただければ、問題ないか確認させていただきます。

よろしくお願いします！

**Comment by aino-capm** [comment]
早速のご回答ありがとうございます。

ご教示いただいた通り、githubにあるrequirement.txtファイルの内容をコピーして、貼り付け直して再デプロイしましたが、同じようなエラーが出ます。
なお、本件に関係があるかどうか分からないのですが、デプロイ中にメモリが不足しているようなメッセージも出ましたので共有します。

どうぞ、よろしくお願いします。

## エラー内容

DOTENV: Loading environment variables from .env:
         - SLACK_SIGNING_SECRET
         - SLACK_BOT_TOKEN
         - SLACK_APP_TOKEN
         - OPENAI_API_KEY
         - OPENAI_API_MODEL
         - OPENAI_API_TEMPERATURE
         - MOMENTO_AUTH_TOKEN
         - MOMENTO_CACHE
         - MOMENTO_TTL

Deploying LangChainBook-ChatGPTSlackFunction to stage dev (ap-northeast-1)

× Stack LangChainBook-ChatGPTSlackFunction-dev failed to deploy (99s)
Environment: linux, node 18.17.1, framework 3.38.0 (local) 3.38.0v (global), plugin 7.2.0, SDK 4.5.1
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
CREATE_FAILED: AppLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: Lambda, Status Code: 400, Request ID: f8e48790-0f58-409a-9394-4c271dec5be3)" (RequestToken: d0327067-e415-1b88-f157-ee32222cb8b9, HandlerErrorCode: InvalidRequest)

View the full error: https://ap-northeast-1.console.aws.amazon.com/cloudformation/home?region=ap-northeast-1#/stack/detail?stackId=arn%3Aaws%3Acloudformation%3Aap-northeast-1%3A123082653093%3Astack%2FLangChainBook-ChatGPTSlackFunction-dev%2F570ab3d0-8bfd-11ee-a649-0e475b115c21

## requirement.txtの内容
aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
async-timeout==4.0.3
attrs==23.1.0
boto3==1.28.49
botocore==1.31.49
certifi==2023.7.22
charset-normalizer==3.2.0
dataclasses-json==0.5.14
frozenlist==1.4.0
greenlet==2.0.2
grpcio==1.58.0
idna==3.4
jmespath==1.0.1
langchain==0.0.292
langsmith==0.0.38
marshmallow==3.20.1
momento==1.9.2
momento-wire-types==0.75.0
multidict==6.0.4
mypy-extensions==1.0.0
numexpr==2.8.6
numpy==1.26.0
openai==0.28.0
packaging==23.1
protobuf==4.24.3
pydantic==2.3.0
pydantic_core==2.6.3
PyJWT==2.8.0
python-dateutil==2.8.2
python-dotenv==1.0.0
PyYAML==6.0.1
requests==2.31.0
s3transfer==0.6.2
six==1.16.0
slack-bolt==1.18.0
slack-sdk==3.22.0
SQLAlchemy==2.0.20
tenacity==8.2.3
tqdm==4.66.1
typing-inspect==0.9.0
typing_extensions==4.8.0
urllib3==1.26.16
yarl==1.9.2

##デプロイ中にでたメッセージ

This environment is running low on memory (71 MB of virtual memory left).
To free up memory, kill processes by choosing "Tools > Process List" in the menu bar.
To migrate this environment to one that has more memory, see [Moving or Resizing an Environment](https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html).

**Comment by os1ma** [comment]
状況共有ありがとうございます。

`Unzipped size must be smaller than 262144000 bytes` とのことで、やはりLambdaにデプロイするパッケージのサイズが大きすぎるエラーになっているようです。

requirement.txtの内容は問題なさそうなので、以下のどちらかの可能性が高そうです。

1. `serverless.yml` ファイルの内容に違いがある
2. `.serverless` ディレクトリのキャッシュの影響

#### 1. `serverless.yml` ファイルの内容に違いがある

まず、serverless.ymlの内容に何か違いがあると、不要なファイル含めデプロイされてしまい、サイズが大きくなりすぎる可能性があります。

serverless.ymlの見本が以下にあるので、参考にしてください。

https://github.com/yoshidashingo/langchain-book/blob/main/chapter7/serverless.yml

とくに以下のあたりが同じ内容か確認してください。

```yml
package:
  patterns:
    - '!.venv/**'
    - '!.env'
    - '!.gitignore'
    - '!.python-version'
    - '!.git/**'
```

#### 2. `.serverless` ディレクトリのキャッシュの影響

ふたつめに、`.serverless` ディレクトリに、エラーになった際の不要なファイルがキャッシュされている可能性があるかもしれません。

`.serverless` ディレクトリを削除して、`serverless deploy` し直してみてください。

#### メモリ不足について

> なお、本件に関係があるかどうか分からないのですが、デプロイ中にメモリが不足しているようなメッセージも出ましたので共有します。

Cloud9の使用状況によってはメモリ不足のメッセージが出ることもあるかもしれません。
そして、メモリ不足がなんらかの影響を及ぼしてエラーになる可能性もあるかもしれません。

たとえば念のためCloud9の環境を再起動したりすると、しばらくはメモリ不足が発生しにくくなるかもしれません。

#### 解決しない場合

もし上記の点を確認いただいて解決しない場合、以下を共有いただきたいです。

- `cat serverless.yml` コマンドの実行結果
- `ls -la` コマンドの実行結果
- Cloud9上に作成したファイルの一覧が分かる画面キャプチャ

よろしくお願いします！

**Comment by aino-capm** [comment]
ありがとうございます！

serverless.ymlのvenvディレクトリの表記が誤っていました。
私の仮想環境は「venv」でした。
serverless.ymlの「.venv」を「venv」に修正したところ、デプロイに成功しました。
こちらも初歩的なミスでした。
ご面倒おかけしました。

デプロイして、Slackアプリがちゃんと動いてくれると感動しますね。
引き続き、どうぞ、よろしくお願いします。

**Comment by os1ma** [comment]
解決してよかったです！
やはり実際に動いてくれると嬉しいですね！
