### ISSUE TITLE
p87 で警告

### ISSUE THREAD

**Issue by icck** [yoshidashingo/langchain-book#8]
**エラーの説明**

エラーではなく警告の共有となります。

from langchain import LLMChain
となっていますが、
from langchain.chains import LLMChain
に変更したほうが良さそうです。

no longer supported.と記載されているので、いつかエラーとなりそうでした。

UserWarning: Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
  warnings.warn(

**スクリーンショット**
![image](https://github.com/yoshidashingo/langchain-book/assets/25297490/6fed2ea7-4911-4d96-a2d6-1aa16d79c2b2)

**書籍の該当箇所**

p87 Chainsのサンプルコード

**書籍の内容以外で実施したこと**

OpenAIではなくBedrockを使って動かしていることは差異となります。

**環境**

vscode, Local+asdf(Python3.11.0)+Poetry
Langchain 0.0.340

**その他**

私が指定されているバージョンより上げすぎたための可能性が高いです。不適切であれば、そのままクローズしていただいて問題ございません。

警告のとおりに修正したところ、警告はなくなりました。
![image](https://github.com/yoshidashingo/langchain-book/assets/25297490/7fd523a4-e314-44fc-a311-7fede4c236a6)

**Comment by os1ma** [comment]
共有ありがとうございます！

> Langchain 0.0.340

書籍の執筆に使用したLangChainのバージョン0.0.292では発生しない警告で、バージョンの差異に起因する内容のようです。

書籍としてはバージョン0.0.292のみサポートということになっていまして、今後より新しいバージョンでコードを書く際に参考にさせていただきます。

ご報告ありがとうございました！
